encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    #path("error", views.error, name="error"),
    path("search", views.search, name="search"),
    path("newpage", views.newpage, name="newpage"),
    path("random", views.randomEntry, name="randomEntry"),
    path("<str:entry>/edit", views.edit, name="edit"),
    path("<str:entry>", views.entry, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse 

import markdown2, random, re

from . import util

wikiTitles = util.list_entries()


class NewPageForm(forms.Form):
    title = forms.CharField(label="Wiki Title")
    entry = forms.CharField(label="Wiki Entry", widget=forms.Textarea)


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry):
    
    '''
    if request.method == "POST":
        form = NewPageForm(request.POST)

        if form.is_valid:
            
            title = form.cleaned_data["title"]
            entry = form.cleaned_data["entry"]

            util.save_entry(title, entry)

            #return render(request)
            return redirect('wiki:entry', entry=title)
    '''    

    wikiEntry = util.get_entry(entry)

    if wikiEntry != None:
        return render(request, "encyclopedia/entry.html", {
            "wikiTitle": entry,
            "wikiEntry": markdown2.markdown(wikiEntry)
        })
    return render(request, "encyclopedia/error.html", {
        "errorRequest": True
    })

def edit(request, entry):
    
    if request.method == "POST":
        form = NewPageForm(request.POST)

        if form.is_valid():
            
            title = form.cleaned_data["title"]
            entry = form.cleaned_data["entry"]

            util.save_entry(title, entry)

            return redirect('wiki:entry', entry=title)
            #return HttpResponseRedirect(reverse("wiki:index"))
    
    else:
        if entry.lower() in [x.lower() for x in wikiTitles]:

            details = util.get_entry(entry)
            
            #data = {'title': entry, 'entry': markdown2.markdown(details)}
            #form = NewPageForm(data) 
            # reference link 
            # https://docs.djangoproject.com/en/3.1/ref/forms/fields/#initial

            form = NewPageForm(initial={'title': entry, 'entry': markdown2.markdown(details)})

            return render(request, "encyclopedia/editpage.html", {
                "item": entry,
                "form": form
            })
        else:
            return render(request, "encyclopedia/error.html", {
                "errorRequest": True
            })


def randomEntry(request):
    wikiTitles = util.list_entries()
    index = random.randrange(0, len(wikiTitles))
    wikiTitle = wikiTitles[index]

    '''
    return render(request, "encyclopedia/entry.html", {
        "wikiTitle": wikiTitle,
        "wikiEntry": markdown2.markdown(util.get_entry(wikiTitle))
    })'''
    return redirect('wiki:entry', wikiTitle)

def newpage(request):
    if request.method == "POST":
        # does this when the data in the textarea is sent by post, after the user has inputted details
        # the code that follows should be similar to the one covered in lecture 3, tasks, specifically add in views.py
        
        #print("it is post!")

        form = NewPageForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data["title"]
            entry = form.cleaned_data["entry"]

            if title.lower in [x.lower() for x in wikiTitles]:
                util.save_entry(title, entry)

                return HttpResponseRedirect(reverse("wiki:index"))
            else:
                return render(request, "encyclopedia/newpage.html", {
                    "form": form,
                    "available": True
                })

    return render(request, "encyclopedia/newpage.html", {
        "form": NewPageForm
    })

def search(request):
    if request.method == "POST":
        term = request.POST
        term = term['q']
        searchList = []

        for item in wikiTitles:
            if item.lower() == term.lower():
                return redirect('wiki:entry', entry=term)

            if re.search(term.lower(), item.lower()):
                searchList.append(item)

        if len(searchList) == 0:
            return render(request, "encyclopedia/error.html", {
                "errorSearch":  True
            })

        return render(request, "encyclopedia/search.html", {
            "result": searchList
        })

def error(request):
    return render(request, "encyclopedia/error.html", {
        "errorRequest": True
    })

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page: {{ item }}
{% endblock %}

{% block body %}
    <h1> Edit Entry! </h1>
    
    <br>

    <form action="{% url 'wiki:edit' item %}" method="post">
        {{ form }}
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary" style="margin-top: 25px;">Save</button>
    </form>
{% endblock %}

<!--  <input type="submit">  -->

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ wikiTitle }}
{% endblock %}

{% block body %}
    {{ wikiEntry|safe }}

    <form action="{% url 'wiki:edit' wikiTitle %}">
        {% csrf_token %}
        <button class="btn btn-outline-secondary">Edit</button>
    </form>

{% endblock %}

<!--  <input type="submit">  -->

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {% if errorRequest %}
        Request Error
    {% endif %}
    {% if errorSearch %}
        Search Error
    {% endif %}
{% endblock %}

{% block body %}
    {% if errorRequest %}
        Requested Page Not Found!
    {% endif %}
    {% if errorSearch %}
        Searched Item Not Found!
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randomEntry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia New Page
{% endblock %}


{% block body %}
    <h1> Add a new Wiki Entry! </h1>

    <br>

    {% if available %}
        <div class="alert alert-danger" role="alert">
            This title already exists. Try a different title.
        </div>
    {%endif%}
    
    <form action="{% url 'wiki:newpage' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    {% for item in result %}
        <li><a href="{% url 'wiki:entry' item %}">{{ item }}</a></li>
    {% endfor %}
{% endblock %}